### PR TITLE
Fixed issue 228

### PR DESCRIPTION
**Pull request by jphellemons**
https://github.com/flagbug/YoutubeExtractor/issues/228
Just like @SomeOneMore said. :)

### CODE REVIEW

**Comment by jphellemons** [comment]
#228 #226

**Comment by flagbug** [comment]
Thanks  @jphellemons !

**Comment by jphellemons** [comment]
It was because @SomeOneMore did a great job :)

**Comment by immersivegamer** [comment]
@flagbug This change doesn't seem to be updated on the Nuget package. Are there plans for it?

I was very confused this weekend as I started out cloning the project but then I used Nuget as the package and project versions were the same. Though when I use the Nuget package I get the 403 errors.

**Pull request merged**
